version: "3.8"

services:
  first-player:
    container_name: first-player
    build: ./
    restart: on-failure
    environment:
      HTTP_SERVER_PORT: 8000
      PING_PONG_SERVICE_PORT: 9000
    ports:
      - 8000:8000
    volumes:
      - ./first/logs:/home/src/logs
    networks:
      - net

  second-player:
    container_name: second-player
    build: ./
    restart: on-failure
    environment:
      HTTP_SERVER_PORT: 9000
      PING_PONG_SERVICE_PORT: 8000
    ports:
      - 9000:9000
    volumes:
      - ./second/logs:/home/src/logs
    networks:
      - net

networks:
  net:
    name: net