http:
  server:
    host: localhost
    port: 8888
    maxHeaderMegabytes: 1
    timeouts:
      read: 5s
      write: 10s
  client:
    timeout: 1s

application:
  ping-pong-service-url: http://host.docker.internal